# Generated by Django 5.2.5 on 2026-01-28 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rust', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rustcontent',
            name='cksum',
            field=models.CharField(db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='rustcontent',
            name='vers',
            field=models.CharField(db_index=True, max_length=64),
        ),
    ]
