# Generated by Django 5.2.11 on 2026-04-23 17:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0149_distributedpublication"),
        ("rust", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="RustContent",
            new_name="RustPackage",
        ),
    ]
