# Generated by Django 5.2.14 on 2026-07-13 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rust', '0003_rustcargotoken'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rustcargotoken',
            options={'default_related_name': '%(app_label)s_%(model_name)s'},
        ),
        migrations.AlterModelOptions(
            name='rustdistribution',
            options={'default_related_name': '%(app_label)s_%(model_name)s', 'permissions': [('manage_roles_rustdistribution', 'Can manage roles on rust distributions'), ('publish_rustdistribution', 'Can publish crates to this distribution'), ('yank_rustdistribution', 'Can yank/unyank crates in this distribution')]},
        ),
    ]
