# Generated by Django 5.2.14 on 2026-08-04 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rust', '0004_alter_rustcargotoken_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rustrepository',
            name='repo_type',
            field=models.CharField(choices=[('cache', 'Caching for pull-through'), ('private', 'Private for uploads')], default='cache', max_length=16),
            preserve_default=False,
        ),
    ]
