# Generated by Django 5.2.14 on 2026-09-29 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rust', '0004_alter_rustcargotoken_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rustcargotoken',
            name='actions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='rustcargotoken',
            name='distributions',
            field=models.ManyToManyField(blank=True, related_name='cargo_tokens', to='rust.rustdistribution'),
        ),
    ]
